# Credenciais
email.user=issmf.grupo2@gmail.com
email.pass=qwgm aluj mhdl dutw

# Configurações do Servidor SMTP
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.smtp.auth=true
email.smtp.starttls.enable=true
email.smtp.ssl.protocols=TLSv1.2

# Regras de Negócio de Email
email.fallback=1252331@isep.ipp.pt, 1252039@isep.ipp.pt, 1251653@isep.ipp.pt
email.dominios.ficticios=issmf.ipp.pt

# Opções: CSV ou SQL
armazenamento.tipo=CSV